java -jar yuicompressor-2.4.7.jar --type css --charset utf-8 ../src/main/webapp/static/css/default.css -o ../src/main/webapp/static/css/default.min.css
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/jquery/jquery-extend.js -o ../src/main/webapp/static/js/jquery/jquery-extend.min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/jquery/jquery.cookie.js -o ../src/main/webapp/static/js/jquery/jquery.cookie.min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/easyui/jquery.easyui.mine.js -o ../src/main/webapp/static/js/easyui/jquery.easyui.mine.min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/easyui/extend/js/easyui-extend.js -o ../src/main/webapp/static/js/easyui/extend/js/easyui-extend.min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/easyui/extend/js/validatebox-extend.js -o ../src/main/webapp/static/js/easyui/extend/js/validatebox-extend.min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/easyui/extend/js/validatebox-ajax.js -o ../src/main/webapp/static/js/easyui/extend/js/validatebox-ajax.min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/easyui/extend/js/easyui-ueditor.js -o ../src/main/webapp/static/js/easyui/extend/js/easyui-ueditor.min.js
java -jar yuicompressor-2.4.7.jar --type css --charset utf-8 ../src/main/webapp/static/js/easyui/extend/icon/easyui-icon.css -o ../src/main/webapp/static/js/easyui/extend/icon/easyui-icon.min.css
java -jar yuicompressor-2.4.7.jar --type css --charset utf-8 ../src/main/webapp/static/js/easyui/extend/icon/eu-icon.css -o ../src/main/webapp/static/js/easyui/extend/icon/eu-icon.min.css
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/easyui/datagridview/datagrid-scrollview.js -o ../src/main/webapp/static/js/easyui/datagridview/datagrid-scrollview.min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/easyui/extend/my97/jquery.easyui.my97.js -o ../src/main/webapp/static/js/easyui/extend/my97/jquery.easyui.my97.min.js
java -jar yuicompressor-2.4.7.jar --type css --charset utf-8 ../src/main/webapp/static/js/easyui/extend/my97/my97.css -o ../src/main/webapp/static/js/easyui/extend/my97/my97.min.css
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/easyui/datagridview/datagrid-scrollview2.js -o ../src/main/webapp/static/js/easyui/datagridview/datagrid-scrollview2.min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/easyui/datagridview/datagrid-bufferview.js -o ../src/main/webapp/static/js/easyui/datagridview/datagrid-bufferview.min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/easyui/datagridview/datagrid-groupview.js -o ../src/main/webapp/static/js/easyui/datagridview/datagrid-groupview.min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/easyui/datagridview/datagrid-defaultview.js -o ../src/main/webapp/static/js/easyui/datagridview/datagrid-defaultview.min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/easyui/extend/app/jquery.app.js -o ../src/main/webapp/static/js/easyui/extend/app/jquery.app.min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/easyui/extend/app/initApp.js -o ../src/main/webapp/static/js/easyui/extend/app/initApp.min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/easyui/portal/jquery.portal.js -o ../src/main/webapp/static/js/easyui/portal/jquery.portal.min.js
java -jar yuicompressor-2.4.7.jar --type css --charset utf-8 ../src/main/webapp/static/js/easyui/portal/portal.css -o ../src/main/webapp/static/js/easyui/portal/portal.min.css
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/js/uploadify/scripts/jquery.uploadify.mine.js -o ../src/main/webapp/static/js/uploadify/scripts/jquery.uploadify.mine.min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/mobile/map_module.js -o ../src/main/webapp/static/mobile/map_module.min.js
java -jar yuicompressor-2.4.7.jar --type js --charset utf-8 ../src/main/webapp/static/mobile/ImageUploader/js/upload_image.js -o ../src/main/webapp/static/mobile/ImageUploader/js/upload_image.min.js
